/*
* mutations
**/
export const ORDERDATA = 'buyerCenter/ORDERDATA'
export const ERRMSG = 'buyerCenter/ERRMSG'
export const WARNMSG = 'buyerCenter/WARNMSG'
export const SHOUYOUORDERLIST = 'buyerCenter/SHOUYOUORDERLIST'
export const MAINGOODSORDERLIST = 'buyerCenter/MAINGOODSORDERLIST'
export const MAINSHOUYOUDETAIL = 'buyerCenter/MAINSHOUYOUDETAIL'
export const PAYSTATUS = 'buyerCenter/PAYSTATUS'
export const MERGEORDERDATA = 'buyerCenter/MERGEORDERDATA'
export const PAGEINDEX = 'buyerCenter/PAGEINDEX'
export const LOADING = 'buyerCenter/LOADING'
export const ISORDERLOADALL1 = 'buyerCenter/ISORDERLOADALL1'
export const ISORDERLOADALL2 = 'buyerCenter/ISORDERLOADALL2'
export const ISORDERLOADALL3 = 'buyerCenter/ISORDERLOADALL3'
export const ISORDERLOADALL4 = 'buyerCenter/ISORDERLOADALL4'
export const CLIST = 'buyerCenter/CLIST'
export const ACCOUNTINFO = 'buyerCenter/ACCOUNTINFO'
export const SERVICEDATA = 'buyerCenter/SERVICEDATA'
export const CENTERCOUNT = 'buyerCenter/CENTERCOUNT'
export const PAYURL = 'buyerCenter/PAYURL'
export const MAYPAYURL = 'buyerCenter/MAYPAYURL'
export const PCIMGINFO = 'buyerCenter/PCIMGINFO'
/*
* actions
**/
export const GETORDERDATA = 'buyerCenter/GETORDERDATA'
export const CLEAR_ERR = 'buyerCenter/CLEAR_ERR'
export const CLEAR_WARN = 'buyerCenter/CLEAR_WARN'
export const MAINSHOUYOUORDERLIST = 'buyerCenter/MAINSHOUYOUORDERLIST'
export const GETMAINGOODSORDERLIST = 'buyerCenter/GETMAINGOODSORDERLIST'
export const GETMAINSHOUYOUDETAIL = 'buyerCenter/GETMAINSHOUYOUDETAIL'
export const GETMAINSHOUYOUFAST = 'buyerCenter/GETMAINSHOUYOUFAST'
export const GETMOBORDERDETAIL = 'buyerCenter/GETMOBORDERDETAIL'
export const CHANGEPAYSTATUS = 'buyerCenter/CHANGEPAYSTATUS'
export const GETMERGEORDERDATA = 'buyerCenter/GETMERGEORDERDATA'
export const SETPAGEINDEX = 'buyerCenter/SETPAGEINDEX'
export const SETLOADING = 'buyerCenter/SETLOADING'
export const CLEARLIST = 'buyerCenter/CLEARLIST'
export const GETACCOUNTINFO = 'buyerCenter/GETACCOUNTINFO'
export const RECHARGEREFUND = 'buyerCenter/RECHARGEREFUND'
export const APPEALSURE = 'buyerCenter/APPEALSURE'
export const APPEALRECEIVE = 'buyerCenter/APPEALRECEIVE'
export const QUERYORDERDETAIL = 'buyerCenter/QUERYORDERDETAIL'
export const GETMOBACCOUNTINFO = 'buyerCenter/GETMOBACCOUNTINFO'
export const MAINGOODSORDERDETAILED = 'buyerCenter/MAINGOODSORDERDETAILED'
export const GETPCACCOUNTINFO = 'buyerCenter/GETPCACCOUNTINFO'
export const OPENSERVICEQQ = 'buyerCenter/OPENSERVICEQQ'
export const GETBUYERMOBCOUNT = 'buyerCenter/GETBUYERMOBCOUNT'
export const GETBUYERPCCOUNT = 'buyerCenter/GETBUYERPCCOUNT'
export const GETBUYERSHOUYOUCOUNT = 'buyerCenter/GETBUYERSHOUYOUCOUNT'
export const GETBUYERMALLCOUNT = 'buyerCenter/GETBUYERMALLCOUNT'
export const MOBILEORDERPAY = 'buyerCenter/MOBILEORDERPAY'
export const CANCELORDER = 'buyerCenter/CANCELORDER'
export const MAYPAY = 'buyerCenter/MAYPAY'
export const GETPCIMGINFO = 'buyerCenter/GETPCIMGINFO'
/*
* getters
**/
