/*
* @Author: fredlee
* @Date:   2017-04-19 13:18:34
* @Last Modified by:   fredlee
* @Last Modified time: 2017-06-28 16:09:35
*/

export const SEARH_GOODS_LIST="SEARH_GOODS_LIST";
export const SELLER_LIST="SELLER_LIST"




/*
* 我要买账号
**/
/*
* mutations
**/
export const GAMELIST = 'choice/GAMELIST'
export const QUICKLIST = 'choice/QUICKLIST'
export const ERRMSG = 'choice/ERRMSG'
export const WARNMSG = 'choice/WARNMSG'
export const PYLIST = 'choice/PYLIST'
export const GAMELISTPY = 'choice/GAMELISTPY'
export const GAMELISTHOT = 'choice/GAMELISTHOT'
export const PAGESTATUS = 'choice/PAGESTATUS'
export const GAMEPAGE = 'choice/GAMEPAGE'
export const SCROLLPOSITION = 'choice/SCROLLPOSITION'
export const GOODSLIST = 'choice/GOODSLIST'
export const PCURL = 'choice/PCURL'
export const GOODSLISTLOADALL = 'choice/GOODSLISTLOADALL'
export const GOODSTYPELIST = 'choice/GOODSTYPELIST'
export const SEARCHGAMELIST = 'choice/SEARCHGAMELIST'
export const GOODSLISTPAGE = 'choice/GOODSLISTPAGE'

export const MUTPOSTDATA = 'choice/MUTPOSTDATA'
export const MUTPLATFORMLIST = 'choice/MUTPLATFORMLIST'
export const MUTGAMEAREAlIST = 'choice/MUTGAMEAREAlIST'
export const MUTGAMESERVERLIST = 'choice/MUTGAMESERVERLIST'
export const MUTFILTERPRETYLIST = 'choice/MUTFILTERPRETYLIST'
export const MUTUPDATEFILTERPRETYLIST = 'choice/MUTUPDATEFILTERPRETYLIST'
export const MUTDEFAULTFILTERPRETYLIST = 'choice/MUTDEFAULTFILTERPRETYLIST'
export const MUTMANYCHOILCE = 'choice/MANYCHOILCE'
export const SUBCHOILCELIST = 'choice/SUBCHOILCELIST'
export const SUBCATELIST = 'choice/SUBCATELIST'
export const CHEKSUBCATESTORE = 'choice/CHEKSUBCATESTORE'
export const MUTCHECKSUBCATE = 'choice/MUTCHECKSUBCATE'

//coomon
export const COMMON_ISLOGIN = 'common/COMMON_ISLOGIN';
//

/*
* actions
**/
export const SEARCH_GAMELIST = 'choice/SEARCH_GAMELIST'
export const CLEAR_ERR = 'choice/CLEAR_ERR'
export const CLEAR_WARN = 'choice/CLEAR_WARN'
export const GET_GAMEPY = 'choice/GET_GAMEPY'
export const GET_GAMELIST_PY = 'choice/GET_GAMELIST_PY'
export const GET_GAMELISTHOT = 'choice/GET_GAMELISTHOT'
export const SET_PAGESTATUS = 'choice/SET_PAGESTATUS'
export const SHOWGAMEPAGE = 'choice/SHOWGAMEPAGE'
export const SAVE_SCROLLPOSITION = 'choice/SAVE_SCROLLPOSITION'
export const GET_LISTDATA = 'choice/GET_LISTDATA'
export const GET_PCURL = 'choice/GET_PCURL'
export const CLEAR_GOODSLIST = 'choice/CLEAR_GOODSLIST'
export const GOODSLISTSCROLLPOSITION = 'choice/GOODSLISTSCROLLPOSITION'
export const SORTACTIVESTATUS = 'choice/SORTACTIVESTATUS'
export const SAVEGOODSLISTSCROLLPOSITION = 'choice/SAVEGOODSLISTSCROLLPOSITION'
export const SORTACTIVE = 'choice/SORTACTIVE'
export const GET_GOODSTYPELIST = 'choice/GET_GOODSTYPELIST'
export const SEARCHGAME = 'choice/SEARCHGAME'
export const SORTSTATUSNAME = 'choice/SORTSTATUSNAME'
export const CLEAR_TYPELIST = 'choice/CLEAR_TYPELIST'
export const SETGOODSLISTPAGE = 'choice/SETGOODSLISTPAGE'
export const GET_QUICKLIST = 'choice/GET_QUICKLIST'
export const GETKEYWORD = 'choice/GETKEYWORD'

//post数据，用于搜索
export const ACTPOSTDATA = 'choice/ACTPOSTDATA'
export const CLEARPOSTDATA = 'choice/CLEARPOSTDATA'
//平台
export const ACTPLATFORMLIST = 'choice/ACTPLATFORMLIST'
export const CLEARPLATFORMLIST = 'choice/CLEARPLATFORMLIST'
//客服端
export const ACTGAMEAREAlIST = 'choice/ACTGAMEAREAlIST'
export const CLEARGAMEAREAlIST = 'choice/CLEARGAMEAREAlIST'
//区服
export const ACTGAMESERVERLIST = 'choice/ACTGAMESERVERLIST'
export const CLEARGAMESERVERLIST = 'choice/CLEARGAMESERVERLIST'

//端游区服
export const ACTPCGAMEAREALIST = 'choice/ACTPCGAMEAREALIST'
export const ACTPCGAMESERVERLIST = 'choice/ACTPCGAMESERVERLIST'
export const GETFILTERPRETYLIST = 'choice/GETFILTERPRETYLIST'
//端游动态属性
export const UPDATEFILTERPRETYLIST = 'choice/UPDATEFILTERPRETYLIST'
export const CLEARFILTERPRETY = 'choice/CLEARFILTERPRETY'
export const MANYCHOILCE = 'choice/MANYCHOILCE'
export const ACTSUBCHOILCELIST = 'choice/ACTSUBCHOILCELIST'

/*
* getters
**/
export const HISTORYGOODSLIST = 'choice/HISTORYGOODSLIST'

export const SCREENPRETY = 'choice/SCREENPRETY'
export const FILTERNUMBERDATA = 'choice/FILTERNUMBERDATA'
export const FILTERBETWEENDATA = 'choice/FILTERBETWEENDATA'
export const FILTERTEXTDATA = 'choice/FILTERTEXTDATA'

//我要卖
export const SELLER_DYNAMIC_LIST = 'seller/SELLER_DYNAMIC_LIST';
export const SELLER_USER_LOGIN = 'seller/SELLER_USER_LOGIN';
export const SELLER_IS_MAINAUTHENTICATION = 'seller/SELLER_IS_MAINAUTHENTICATION';
export const SELLER_REPOSITORYNUM = 'seller/SELLER_REPOSITORYNUM';
export const SELLER_UNIT = 'seller/SELLER_UNIT';

//我是卖家商品
export const MEMBER_SELLER_COUNT_LIST = 'member/MEMBER_SELLER_COUNT_LIST';
export const MEMBER_SELLER_MOBILE_LIST = 'member/MEMBER_SELLER_MOBILE_LIST';
export const MEMBER_SELLER_CLEAR_MOBILELIST = 'member/MEMBER_SELLER_CLEAR_MOBILELIST';
export const MEMBER_SELLER_CLEAR_PCLIST = 'member/MEMBER_SELLER_CLEAR_PCLIST';
export const MEMBER_SELLER_GETCONF = 'member/MEMBER_SELLER_GETCONF';
export const MEMBER_SELLER_GOODS_DETAIL = 'member/MEMBER_SELLER_GOODS_DETAIL';
export const MEMBER_SELLER_GOODS_MOBILE_PUBLICSTATE = 'member/MEMBER_SELLER_GOODS_MOBILE_PUBLICSTATE';
export const MEMBER_SELLER_PC_LIST='member/MEMBER_SELLER_PC_LIST';
export const MEMBER_SELLER_GOODS_PC_PUBLICSTATE = 'member/MEMBER_SELLER_GOODS_PC_PUBLICSTATE';
export const MEMBER_SELLER_GOODS_UPDATE_STATUS = 'member/MEMBER_SELLER_GOODS_UPDATE_STATUS'
//我是买家订单
export const MEMBER_SELLER_ORDER_MOBILE_LIST = 'member/MEMBER_SELLER_ORDER_MOBILE_LIST';
export const MEMBER_SELLER_ORDER_MOBILE_CLEAR_LIST = 'member/MEMBER_SELLER_ORDER_MOBILE_CLEAR_LIST';
export const MEMBER_SELLER_ORDER_MOBILE_STATE = 'member/MEMBER_SELLER_ORDER_MOBILE_STATE';
export const MEMBER_SELLER_ORDER_PC_LIST = 'member/MEMBER_SELLER_ORDER_PC_LIST';
export const MEMBER_SELLER_ORDER_PC_CLEAR_LIST = 'member/MEMBER_SELLER_ORDER_PC_CLEAR_LIST';
export const MEMBER_SELLER_ORDER_COUNT_LIST =  'member/MEMBER_SELLER_ORDER_COUNT_LIST';
export const MEMBER_SELLER_ORDER_MOBILE_DETAIL = 'member/MEMBER_SELLER_ORDER_MOBILE_DETAIL';
export const MEMBER_SELLER_ORDER_PC_STATE = 'member/MEMBER_SELLER_ORDER_PC_STATE';
export const MEMBER_SELLER_ORDER_PC_DETAIL = 'member/MEMBER_SELLER_ORDER_PC_DETAIL';
